services:
  dnsserver:
    build: dnsserver
    hostname: darthvader
    networks:
      rededns:
          ipv4_address: 192.168.20.10
    volumes:
      - ./dnsserver/conf/named.conf.options:/etc/bind/named.conf.options
# Esto de arriba primero se descarga, luego se monta el volumen. Eso pq docker siempre piensa que lo de la izq es una cpta
  eq1:
    build: debian
    hostname: eq1
    dns:
      - 192.168.20.10
    networks:
      rededns:
          ipv4_address: 192.168.20.100
networks:
  rededns:
    ipam:
      config:
        - subnet: 192.168.20.0/24

